### ISSUE TITLE
CacheImpl.setSilently() may not work under certain circumstances.

### ISSUE THREAD

**Issue by koo-taejin** [ragnor/simple-spring-memcached#100]
Hello, @ragnor 

#### description 
I guess that CacheImpl.setSilently() has a function that ignores failures in cache operations.

However, in the following environment, setSilently() does not work properly.
```
    at net.spy.memcached.internal.OperationFuture.get(OperationFuture.java:142)
    at com.google.code.ssm.providers.spymemcached.MemcacheClientWrapper.set(MemcacheClientWrapper.java:262)
    at com.google.code.ssm.CacheImpl.set(CacheImpl.java:290)
    at com.google.code.ssm.CacheImpl.set(CacheImpl.java:128)
    at com.google.code.ssm.CacheImpl.setSilently(CacheImpl.java:141)
```

This is because OperationFuture.get() throws a RunTimeException.
(https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/internal/OperationFuture.java#L138)

In this regard, I am going to send to this project a simple PR.

By the way, is the project disabled?

**Comment by ragnor** [comment]
Hi,

The CacheImpl.setSilently() should work as expected, the RuntimeException from OperationFuture.get() is handled by MemcacheClientWrapper#266 (MemcacheClientWrapper.mapAndRethrow) and then rethrown as TimeoutException, the exception is logged as warn in setSilently.
The project is active. I'm open to PRs

**Comment by koo-taejin** [comment]
Sorry @ragnor ,

The code I am using is the version before v4.1.3, and I searched for it by the class name and checked it, but I did not recognize that the same class name existed.

I am going to use fixed version.

Thank you :)
