### ISSUE TITLE
Guice support

### ISSUE THREAD

**Issue by ssm-user** [ragnor/simple-spring-memcached#19]
_From [Ben.Ma...@gmail.com](https://code.google.com/u/116561040243839055672/) on June 29, 2013 09:34:02_

It would be beneficial if SSM supported Guice as an alternative to Spring. The dependency injector library should be an add-on.

The primary challenge appears to be the use of AspectJ advices instead of AOPAlliance's method interceptors. There is probably an adapter scheme, as Spring supports both, so that Guice's AOPAlliance support can be leveraged. I haven't figured out that detail, though.

_Original issue: http://code.google.com/p/simple-spring-memcached/issues/detail?id=19_

**Comment by ragnor** [comment]
Closing the issue as there hasn't been any more requests to support Guice. SSM highly relay on Spring so adding support of Guice requires a lot of work.
