### ISSUE TITLE
Can I Disable SSM via property override

### ISSUE THREAD

**Issue by zzk6205** [ragnor/simple-spring-memcached#39]
SSM can be disabled by using system property: ssm.cache.disable=true.
But it seems like editing catalina.sh will be more inconvenient than what we are already doing (we comment out the memcached configuration in xml and try to remember not to check it in).
Consider this a feature request for the ability to turn SSM off via bean configuration i.e.:

```
<bean name="globalSSMSettings" class="com.google.code.ssm.Settings">
   <property name="disable" value="true"/>
 </bean>
```

**Comment by MauOnline** [comment]
Hello,
Is it possible to have a full working example, please? Google starts being a giant mess with a lot of deprecated information.

**Comment by ragnor** [comment]
Here you are, full SSM configuration (3 caches, spymemcached , caching disabled, integration with Spring):

`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:context="http://www.springframework.org/schema/context" xmlns:cache="http://www.springframework.org/schema/cache"
	xsi:schemaLocation="
		   http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans-3.1.xsd
           http://www.springframework.org/schema/context
           http://www.springframework.org/schema/context/spring-context-3.1.xsd
           http://www.springframework.org/schema/cache 
           http://www.springframework.org/schema/cache/spring-cache-3.1.xsd">

	<cache:annotation-driven />

	<context:annotation-config />
	<context:component-scan base-package="com.google.code.ssm.spring.test" />

       <bean name="globalSSMSettings" class="com.google.code.ssm.Settings">
           <property name="disableCache" value="true"/>
        </bean>

	<bean name="cacheManager" class="com.google.code.ssm.spring.SSMCacheManager">
		<property name="caches">
			<set>
				<bean class="com.google.code.ssm.spring.SSMCache">
					<qualifier value="userCache"/>
					<constructor-arg name="cache" index="0" ref="userCache" />
					
					<constructor-arg name="expiration" index="1" value="300" />
					
					<constructor-arg name="allowClear" index="2" value="false" />
				</bean>
				<bean class="com.google.code.ssm.spring.SSMCache">
					<constructor-arg name="cache" index="0" ref="clearableCache" />
					
					<constructor-arg name="expiration" index="1" value="300" />
					
					<constructor-arg name="allowClear" index="2" value="true" />
				</bean>
				<bean class="com.google.code.ssm.spring.SSMCache">
					<constructor-arg name="cache" index="0" ref="testCache" />
					
					<constructor-arg name="expiration" index="1" value="300" />
					
					<constructor-arg name="allowClear" index="2" value="true" />
				</bean>
			</set>
		</property>
	</bean>

	<bean name="userCache" class="com.google.code.ssm.CacheFactory">
		<property name="cacheName" value="userCache" />
		<property name="cacheClientFactory" ref="cacheClientFactory"/>
		<property name="addressProvider">
			<bean class="com.google.code.ssm.config.DefaultAddressProvider">
				<property name="address" value="127.0.0.1:11211" />
			</bean>
		</property>
		<property name="configuration" ref="clientConfig" />
	</bean>

	<bean name="clearableCache" class="com.google.code.ssm.CacheFactory">
		<property name="cacheName" value="clearableCache" />
		<property name="cacheClientFactory" ref="cacheClientFactory"/>
		<property name="addressProvider">
			<bean class="com.google.code.ssm.config.DefaultAddressProvider">
				<property name="address" value="127.0.0.1:11212" />
			</bean>
		</property>
		<property name="configuration" ref="clientConfig" />
	</bean>
	
	<bean name="testCache" class="com.google.code.ssm.CacheFactory">
		<property name="cacheName" value="testCache" />
		<property name="cacheClientFactory" ref="cacheClientFactory"/>
		<property name="addressProvider">
			<bean class="com.google.code.ssm.config.DefaultAddressProvider">
				<property name="address" value="127.0.0.1:11211" />
			</bean>
		</property>
		<property name="configuration" ref="clientConfig" />
	</bean>

		<bean name="cacheClientFactory" class="com.google.code.ssm.providers.spymemcached.MemcacheClientFactoryImpl" />
		<bean name="clientConfig" class="com.google.code.ssm.providers.CacheConfiguration">
			<property name="consistentHashing" value="true" />
		</bean>
</beans>`

**Comment by MauOnline** [comment]
Geat, thank you very much!
