### ISSUE TITLE
JUnit not a test scope dependency in pom.xml

### ISSUE THREAD

**Issue by ecbrodie** [ragnor/simple-spring-memcached#47]
Just realized that JUnit was not set as a test scope dependency in the parent pom.xml file of this project. This meant that I had to configure an explicit exclusion on my own project when adding simple-spring-memcached to my project, since the JUnit dependency was leaking into my own classpath at runtime. I will create a Pull Request to get this fixed.

**Comment by ragnor** [comment]
Could you provide me a more details about it?
Parent pom.xml defines only dependencyManagement section but it doesn't mean that all children modules require defined defined dependencies. It's only specify what version will be used if a child module use the dependency. If you check pom in child modules then you see that junit is added with test scope.

**Comment by ecbrodie** [comment]
Okay, I looked a little further and it looks like the compile-time dependency from junit came from one of the downstream dependencies of simple-spring-memcached: com.amazonaws:elasticache-java-cluster-client. I will contact them to see if they can fix this issue. In the meanwhile, I suggest for this project that you set an exclusion on this dependency so that you are not pulling in junit nor junit-dep in compile time.

**Comment by ragnor** [comment]
Now it's clear. I'll exclude it from aws-elasticache-provider.
Thanks for checking it.

**Comment by ecbrodie** [comment]
Want me to do it and submit as a pull request? Or will you do it?

**Comment by ragnor** [comment]
Please submit a pull request if you want. The change is quite obvious but I'd like to see more community commitment to the project.
