### ISSUE TITLE
settings bean disableCache value is not honoured

### ISSUE THREAD

**Issue by pgokul** [ragnor/simple-spring-memcached#48]
The settings bean globalSSMSettings is queried after the caches have been created in cacheBase afterPropertiesSet. This effectively results in globalSSMSettings disableCache not being honored.

**Comment by ragnor** [comment]
Have you noticed any request to the memcached when the disableCache property is set to true? 

When disableCache property is set some SSM classes/beans are still initialized but there are no request to memcached instance. Take a look at https://github.com/ragnor/simple-spring-memcached/blob/master/simple-spring-memcached/src/main/java/com/google/code/ssm/CacheFactory.java. It creates Cache but the created object is only stub of the Cache. Also each *Advice class (e.g. https://github.com/ragnor/simple-spring-memcached/blob/master/simple-spring-memcached/src/main/java/com/google/code/ssm/aop/SingleReadCacheAdvice.java) before applying  a caching to a method checks if cache is disabled.

**Comment by pgokul** [comment]
we noticed connections to memcached server were happening. In our case when we disable cache the memcache endpoint is also invalid so we can see a lot of connection errors.
The cache factory stub cache is not created since the settings object is read after the cache creation.

**Comment by ragnor** [comment]
Does it change anything if you use system property ssm.cache.disable=true instead of globallSSMSettings?

**Comment by pgokul** [comment]
yes. connections to the memcached server were not happening if the property ssm.cache.disable=true was set.

**Comment by pgokul** [comment]
We are using spring's Cacheable annotation and when the cache is disabled we are getting an IllegalStateException from DisabledCacheInvocationHandler when getProperties is invoked. Is this expected behaviour.

**Comment by ragnor** [comment]
Thank you for the patch. It has been merged to master.

**Comment by jamsesso** [comment]
Would it be possible to release this patch in a revision release instead of waiting for 3.7.0 because it is a bug fix and not new functionality?

**Comment by ragnor** [comment]
New version 3.6.1 with bugfixes has been released
