### ISSUE TITLE
Documenting `depends-on="cacheBase"` problem for 3.6.0

### ISSUE THREAD

**Issue by nilguncelik** [ragnor/simple-spring-memcached#52]
In this stackoverflow question <http://stackoverflow.com/a/32090183/572380/>, you state that 

> There is an error in SSM 3.6.0, please downgrade to 3.5.0 to solve the issue or try to add
>  depends-on="cacheBase"
> to defaultCache bean definition.

I think we should add this to documentation or examples where anyone can see and save some precious hours :)

( I noticed this is mentioned in comments section of Getting Started documentation, but it is hardly visible for everyone to notice. )

**Comment by ragnor** [comment]
Thank your for your comment. I'll fix it in upcoming release 3.7.0
