### ISSUE TITLE
Does "CacheFactory" support the connection pool feature?

### ISSUE THREAD

**Issue by chrishu123** [ragnor/simple-spring-memcached#56]
Does the CacheFactory or CacheConfiguration support the "pool" setting?

Because I want to use the connection as following style:
pool.setMinConn( 5 );
pool.setMaxConn( 250 );
pool.setMaintSleep( 30 );  
pool.setNagle( false );

**Comment by chrishu123** [comment]
I will use this connection into my spring project, so we want to evaluate it's performance, but it seems not support the pool feature.

**Comment by chrishu123** [comment]
I got figured it out by myself, by using:
private XMemcachedConfiguration config() {
		XMemcachedConfiguration cacheConfiguration = new XMemcachedConfiguration();
		cacheConfiguration.setConnectionPoolSize(properties
				.getConnectionPoolSize());
		cacheConfiguration.setConnectionTimeout(properties.getConnectTimeout());
		cacheConfiguration.setConsistentHashing(properties
				.isConsistentHashing());
		return cacheConfiguration;
}

this is a good project and we have merged it into our dev framework

**Comment by ragnor** [comment]
You've found a valid approach. CacheFactory and CacheConfiguration aren't pooled because underlying providers: spymemcached, xmemcached provides pooling features.
