### ISSUE TITLE
Allow custom key generator

### ISSUE THREAD

**Issue by minghuiliu2008** [ragnor/simple-spring-memcached#57]
The cache key generator should take method return type, annotation data, method args as parameters and the library should allow customer cache key generator to be configured. Simimlar to ehcache:

<cache:annotation-driven key-generator="backEndKeyGenerator" />

**Comment by ragnor** [comment]
It's possible to set custom cache key generator. It can be done globally by invoking com.google.code.ssm.aop.CacheBase.setCacheKeyBuilder and passing own implementation of com.google.code.ssm.aop.support.CacheKeyBuilder.

**Comment by minghuiliu2008** [comment]
Hi Ragnor,
Thanks for your reply. The interface should allow return data type to be a parameter. At the moment, the interface method:
String getCacheKey(final AnnotationData data, final Object[] args, final String methodDesc) throws Exception;

I would like it to have one extra parameter:

String getCacheKey(final Object return, final AnnotationData data, final Object[] args, final String methodDesc) throws Exception;

As I don't want development to use annotation schema attribute, I want to do a generic key using the object type it the method retuned.

**Comment by minghuiliu2008** [comment]
Actually no worries. I used your spring-cache library and as such, I can use Spring's cache annotations e.g. @Cacheable. And Spring cache allows custom key generator.

**Comment by minghuiliu2008** [comment]
Hence close this issue. Thanks for your help!

**Comment by ragnor** [comment]
Glad to hear that you've found a solution.
