### ISSUE TITLE
SSMCacheManager class compile error

### ISSUE THREAD

**Issue by copywrite** [ragnor/simple-spring-memcached#59]
![image](https://cloud.githubusercontent.com/assets/2314482/15353366/495074c2-1d1b-11e6-8fe7-9411b2637c14.png)

check the snapshot plz.

**Comment by ragnor** [comment]
Please provide more detail about the error. What version of java do you use?
SSM snapshot compiles without errors on CI: https://ragnor.ci.cloudbees.com/

**Comment by copywrite** [comment]
Hi ragnor.
I figured it out yesterday. 
Iombok annotation needs an extra plugin under intellij IDE.
Thx anyway.
