### ISSUE TITLE
Any suggestions on nested call?

### ISSUE THREAD

**Issue by copywrite** [ragnor/simple-spring-memcached#60]
Hi ragnor.

I might write such code as

```
public class Foo() {
    @ReadThroughSingleCache
    public Bar read() {
        return new Bar();
    }

   public Bar anotherRead() {
       return read();
   }
}
```

As SSM is based on Spring AOP.

I found some reference.

http://stackoverflow.com/questions/13564627/spring-aop-not-working-for-method-call-inside-another-method

However, Are there any suggestions on SSM of this issue .

**Comment by ragnor** [comment]
Hi,

SSM uses proxy based beans so invocation through 'this' are not intercepted and not cached. 
As a solution (not perfect) is to replace all 'this' with reference to bean:
```
public class Foo() {
    @Autowired
    private Foo foo;

    @ReadThroughSingleCache
    public Bar read() {
        return new Bar();
    }

   public Bar anotherRead() {
       return foo.read();
   }
}
```

**Comment by copywrite** [comment]
Hi ragnor: 
Good advice, much better than the stackoverflow reference.
Thank you for your assistance.
