### ISSUE TITLE
Clarification about Spring cache evict allEntries

### ISSUE THREAD

**Issue by ahmednasir91** [ragnor/simple-spring-memcached#63]
In a spring project, if we are using a single cache server and different cache managers an eg annotation is 
`@Cacheable(value = "configCache", key="#key")`
`@Cacheable(value = "envCache", key="#key")`
and if we do
`@CacheEvict(value = "configCache", allEntries=true)` and if we have enabled `allowClear=true` in the configuration, so will this only evict the `configCache`? or it will clear `envCache` as well?

**Comment by ragnor** [comment]
If will also clear *envCache* if it's on the same memcached instance/server as *configCache*. 
Because memcached doesn't support namespaces only all keys can be removed from the instance.

**Comment by ahmednasir91** [comment]
Thanks for your help.
