### ISSUE TITLE
Defining SerializationType for use by SSMCache

### ISSUE THREAD

**Issue by mdewilde** [ragnor/simple-spring-memcached#66]
For storing an object that does not implement Serializable, we've created a custom CacheTranscoder that uses Kryo.
However, it seems it is currently not possible to have the simple-spring-memcached library use that CacheTranscoder implementation with SSMCache.
The only call from SSMCache to add an item to the cache passes null as SerializationType, making it impossible to instruct lower levels to use our transcoder:

    @Override
    public void put(final Object key, final Object value) {

        [...]

        cache.set(cacheKey, expiration, store, null);

Is it possible I'm overlooking something? Alternatively, would it be possible to add this ability?

Thank you for your work.

**Comment by ragnor** [comment]
It's possible to switch to your custom transcoder but you cannot make it selectively (only for some methods). 

Please take a look at `com.google.code.ssm.CacheFactory` there are two useful properties: `defaultSerializationType` and `customTranscoder`. The first one you need to set to `SerializationType.CUSTOM`, the second one should point to your kryo CacheTranscoder bean.
