### ISSUE TITLE
SSMCache with never expire

### ISSUE THREAD

**Issue by V1cHu** [ragnor/simple-spring-memcached#68]
I could not find anywhere in the wiki or documentation on where to set the SSMCache to not expire at all, rather than the purge. However I could find this :

> Also note: a value of 0 means the given value should never expire. The value is still susceptible to purging by memcached for space and LRU (least recently used) considerations.

in [UpdateSingleCache.java](https://github.com/ragnor/simple-spring-memcached/blob/f203e1ecd564d4a001b630bbacd49abeece41b9d/simple-spring-memcached/src/main/java/com/google/code/ssm/api/UpdateSingleCache.java)

Does that mean SSMCache will also accept the value of 0 for a never expire cache ?

**Comment by ragnor** [comment]
Yes, SSMCache should accept 0 for a never expire cache.
Have you noticed a different behavior?
