### ISSUE TITLE
Don't find a way to do same as AbstractRoutingDataSource

### ISSUE THREAD

**Issue by nikhil-dhiman** [ragnor/simple-spring-memcached#70]
On the basis of some sitecode[TenantId] i want to route to particular memcache address. Is that possible in this. 
I wanted same functionality as of AbstractRoutingDataSource.

**Comment by ragnor** [comment]
SSM is an caching layer that support integration with Spring Cache abstraction. It doesn't control distribution of keys and values across multiple memcached servers instead an external libraries are used: xmemcached and spymemcached. Take a look at their features and documentations.
