### ISSUE TITLE
Environment as prefix

### ISSUE THREAD

**Issue by avanathan** [ragnor/simple-spring-memcached#74]
Hi @ragnor I would like to pass environment - eg. qa, e2e, perf etc., as prefix to the cache keys created. Currently it is generating keys with - alias+key. It would be great if we can generate it like env:alias:key.  

I tried to create an extension to CacheKeyBuilderImpl and set it to CacheBase. But it doesn't seem to be working.

In my CustomCacheKeyBuilderImpl, i overrode just one method

`getCacheKey(final Object keyObject, final String namespace)` to return 
`env + SEPARATOR + namespace + SEPARATOR + defaultKeyProvider.generateKey(keyObject);`

Also there are some private fields and methods in CacheKeyBuilderImpl which doesn't let me extend this class cleanly. But that is not a big deal.

Any help would be appreciated.

Thanks

**Comment by ragnor** [comment]
Have you assigned instance of CustomCacheKeyBuilder to CacheBase?
You have to invoke:
`cacheBase.setCacheKeyBuilder(new CustomCacheKeyBuilderImpl());`

As you have noticed the fields are private so you cannot use SEPARATOR, you need to define it once again in subclass. 
To make the implementation consistent make sure that all methods of CacheKeyBuilder interface are changed. The implementation should be easy as you can use CacheKeyBuilderImpl and just prefix generated string with env variable like:

```
@Override
public String getCacheKey(final Object keyObject, final String namespace) {
   return env + SEPARATOR + cacheKeyBuildeImpl.getCacheKey(keyObject, namespace);
}
```
