### ISSUE TITLE
Reconnect to failing node not happening

### ISSUE THREAD

**Issue by YashchenkoN** [ragnor/simple-spring-memcached#76]
We use the version 4.0.0 of this library with Spymemcached. Everything works fine besides reconnection issues.
We have 2 docker containers: the container with Memcached itself (so only one node of MC in our app) and the container with Spring Boot microservice. Microservice connects to Memcached through the library and works well. Then we stop Memcached container and try to do some operation in microservice, it causes connection timeout:

```
net.spy.memcached.OperationTimeoutException: Timeout waiting for value: waited 5,000 ms. Node status: Connection Status { /10.1.0.3:11211 active: false, authed: true, last read: 750 ms ago }
```

After that, we start MC container and wait until it starts. Then we make some operation in microservice, it tries to connect to Memcached but unsuccessfully: the same error as above, despite that MC instance is up and running.

So, this means that library doesn't try to reconnect to live MC server after the timeout issues.

I've found almost the same issue on SO: https://stackoverflow.com/a/22343555/5207023 but setting TimeoutExceptionThreshould didn't help me.

So the question here: is this expected behavior? How to make a client`s connection reconnect in case of failures?

**Comment by ragnor** [comment]
Have you observed the same issue for XMemcached.

**Comment by ragnor** [comment]
@YashchenkoN Any progress on it?

**Comment by YashchenkoN** [comment]
@ragnor I've found that this issue is reproducible only with ClientMode.Static. If ClientMode is set to Dynamic, everything works as expected. So, I think it's likely a configuration issue rather than an issue with a library and the ticket can be closed now.
