### ISSUE TITLE
Issue in constructing SSMCache in SSMCacheManager when isUseNameAsKeyPrefix() is true

### ISSUE THREAD

**Issue by swetanahata** [ragnor/simple-spring-memcached#77]
The method getCache as shown below in SSMCacheManager doesn't pass muteExceptions property when construction new SSMCache() if isUseNameAsKeyPrefix() is true.

```
public SSMCache getCache(final String name) {
        SSMCache cache = (SSMCache) this.cacheMap.get(name);
        if (cache == null) {
            return null;
        }

        if (cache.getCache().getProperties().isUseNameAsKeyPrefix()) {
            return new SSMCache(new PrefixedCacheImpl(cache.getCache(), name, cache.getCache().getProperties().getKeyPrefixSeparator()),
                    cache.getExpiration(), cache.isAllowClear());
        }

        return cache;
    }
````

This is causing an issue wherein even if we set muteExceptions to true when useNameAsKeyPrefix is set to true it is treated as false.
Can we please fix this?

**Comment by ragnor** [comment]
Thanks for the bug report. It will be fixed in next minor/bug release.

**Comment by ragnor** [comment]
Fixed on master.
