### ISSUE TITLE
Make addCache method in SSMCacheManager public

### ISSUE THREAD

**Issue by swetanahata** [ragnor/simple-spring-memcached#78]
Can you please make addCache method in SSMCacheManager public? This is needed to be able to dynamically add new caches via code as opposed to setting them via configuration.

**Comment by ragnor** [comment]
New methods have been added to SSMCacheManagetr.
@swetanahata  Please test the methods and let me know if it fulfills your needs.

**Comment by swetanahata** [comment]
Thanks @ragnor . Yes, this works for me. Can you please let me know when will the next version be released so that I can start using the same?

**Comment by ragnor** [comment]
@swetanahata Related code has been released.
