### ISSUE TITLE
Per cache key expiry not working as expected

### ISSUE THREAD

**Issue by seeksree** [ragnor/simple-spring-memcached#79]
Hi, 
We are using simple-spring-memcached.version 3.6.1 in our project.The cache key pattern that we use is as follows.

keyname#180#<identifier>

Note that the expiry time in seconds for the key is specified after  the first '#' character. We are using ExtendedSSMCacheManager that allows us to pass the expiration time.
We also have the default expiration set via SSMCache constructor.

We have observed that, for the specific cache key mentioned above, the expiry mentioned as part of the key does not seem to take effect. Instead it always takes the default expiry time specified while creating the SSMCache. This was working in our previous releases of our product and suddenly stopped working. Though the 
simple-spring-memcached.version has remained the same, the memcached server version has changed from 1.4.4 to 1.5.6.

We are wondering if there is an known issue or is this a bug with simple-spring-memcached.version 3.6.1  integration with Memcached 1.5.6 with respect to the above scenario. Thanks.

**Comment by ragnor** [comment]
Hi,

Could you please check if the problem occurs on latest version of SSM: 4.0.0?

**Comment by seeksree** [comment]
Hi raGnoR,

Thanks for the reply. Sorry, I actually meant cache name instead of keyname. So, we are basically registering the cache name aliases that has the pattern as say <cachename#180> to the cache manager. Let me post the exact code that we use tomorrow. sure, I'll also try to check with 4.0.0.

Thanks,
Srikkanth

**Comment by ragnor** [comment]
Closing the issue as information hasn't been provided.
