### ISSUE TITLE
Deserialization from cache fails when using spring-dev-tools in addition to simple-spring-memcached

### ISSUE THREAD

**Issue by koder** [ragnor/simple-spring-memcached#82]
Adding spring-dev-tools dependency in maven and using simple-spring-memcached, deserialization fails with errors:
java.lang.ClassCastException: com.mypackage.MyClass cannot be cast to com.mypackage.MyClass.

According to spring-dev-tools doc, this is a known limitation that should be handled by cache provider:
https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-known-restart-limitations

I have to remove spring-dev-tools to make it work.

**Comment by ragnor** [comment]
Could you share your sample project to reproduce the issue?

**Comment by ragnor** [comment]
Fixed on master, the issue occured only when java transcoder were used
