### ISSUE TITLE
What about cache data expiring

### ISSUE THREAD

**Issue by WhisperRain** [ragnor/simple-spring-memcached#85]
Sometimes the data in DB will change value. So cache data has a  TTL( time to live). The cache data needs to refresh when it expires

**Comment by ragnor** [comment]
The data in cache can be expired in couple of ways:
- set expiration parameter on annotations @ReadThrough*Cache
- set default expiration by using constructor parameter when creating _com.google.code.ssm.spring.SSMCache_
- use _ExtendedSSMCacheManager_ to define custom expiration on each method (in @Cacheable) as a cache name use concatenation of specific cache name, separator (by default #) and expiration 
- manually overwrite value using @Update*Cache or @CachePut
- manually remove value using @Invalidate*Cache or @CacheEvict

**Comment by WhisperRain** [comment]
@ragnor  Thank you so much!
 If it can automatically refresh and remove old value, it would be better.
