### ISSUE TITLE
can we disable SSM cache through annotations or through properties file in spring boot ?

### ISSUE THREAD

**Issue by pj-vvs** [ragnor/simple-spring-memcached#87]
I have two queries 
1. Is there any possibility to use memcache when I need for some period of time and disable for some period of time? If I disable memcache, every time it needs to be fetch from DB.If I enable, first it should flush cache and start caching DB data.

2.In spymemcached,  exceptions are handling internally and printing as warning messages(example is, if one of memcached server goes down). I would like to handle those exceptions in my code. is there any way to do ?

Thank you in advance.

**Comment by ragnor** [comment]
Hi,

1. What kind of annotations do you use (Spring or SSM)? How many methods are cached/interrupted?
2. In case of connection lost you can use net.spy.memcached.ConnectionObserver that can be set in SpymemcachedConfiguration.

**Comment by pj-vvs** [comment]
Hi,

Thank you for your quick response.

1.I am using SSM annotations. I need for all methods.

2.can you provide me small snippet for ConnectionObserver.

**Comment by ragnor** [comment]
1. You can disable caching in SSM by creating custom bean of _type com.google.code.ssm.Settings_ . It contains property _disableCache_ that can be changed in runtime. To make sure that old data aren't used, before enabling cache you have to clean memcached. It can be achieved by using _com.google.code.ssm.Cache.flush()_. It will remove **ALL** data from memcached instance. 
2. Here is source code of ConnectionObserver: https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/ConnectionObserver.java. Just create object of this type a set on _SpymemcachedConfiguration_.

**Comment by pj-vvs** [comment]
Thank you for ample of information..

Solved all issues , but here ConnectionOberver is an interface..How to create an object for this.Do I need to implement methods in it?

**Comment by pj-vvs** [comment]
A).How to declare annotations(ReadThrough*Cache, Update*Cache, Invalidate*Cache) for query methods in JPA repository or CrudRepository.
B).How to clear/ flush data for particular namespace. (if I use flush(), it is clearing all data from memcached server).

**Comment by ragnor** [comment]
A) Take a look at https://github.com/ragnor/simple-spring-memcached/issues/80, you have to enable proper property on Settings and in case of generic interface provide additional configuration of bridge methods
B) Namespaces are some logic concept available only in SSM. Namespaces are not supported by memcached so you can only flush all data from the server. You might consider using multiple memcached servers and deploy each namespace to a different server.

**Comment by pj-vvs** [comment]
Bingo!!

Thank you for valuable info.  👍  :)
