### ISSUE TITLE
SSMCache.flush clears all caches on the memcached server instead of the individual cache

### ISSUE THREAD

**Issue by thorntonrp** [ragnor/simple-spring-memcached#89]
When invoking `SSMCache.clear()`, the expectation is that it will only clear entries from the specific cache named by `SSMCache.getName()`. Instead, it flushes all entries across all caches on the Memcached server.

**Comment by ragnor** [comment]
Please take a look at documentation: https://github.com/ragnor/simple-spring-memcached/wiki/Getting-Started#settings.
Memcached doesn't support cache zones or cache namespaces, so there's no such operation like clearing only some part of data stored in zone/namespace, only all data stored by memcached instance can be removed
