### ISSUE TITLE
Getting NullPointerException in MemcachedConnector$SessionMonitor.run continuously .

### ISSUE THREAD

**Issue by rasikhinge** [ragnor/simple-spring-memcached#94]
Hello,

we are using Simple-Spring-memcached in one of our microservice implemented using springboot.

we have below configuration - 
```
 final ElastiCacheConfiguration conf = new ElastiCacheConfiguration();
        conf.setConsistentHashing(true);
        conf.setOperationTimeout(timeoutValue);
        conf.setClientMode(ClientMode.Dynamic);
        final CacheFactory cf = new CacheFactory();
        cf.setCacheClientFactory(new com.google.code.ssm.providers.xmemcached.MemcacheClientFactoryImpl());
        cf.setAddressProvider(new DefaultAddressProvider(serverhost));
        cf.setConfiguration(conf);
        return cf;
```
		

When `serverhost` in above config, is not accessible or not available.
We are continuously receiving below exception - 

java.lang.NullPointerException: null
	at net.rubyeye.xmemcached.impl.MemcachedConnector$SessionMonitor.run(MemcachedConnector.java:120)

[-Session-Thread] c.g.c.y.core.impl.AbstractController     : Reconnected to no_default_cache_replica:10000 fail
[-Session-Thread] c.g.c.y.core.impl.AbstractController     : Reconnected to no_default_cache_replica:10000 fail
[-Session-Thread] c.g.c.y.core.impl.AbstractController     : SessionMonitor connect error

how to handle this scenario ? do we have configuration to stop polling the server ? - I am looking to keep the cache log silent when server is not accessible or is in error, as anyway non cache response will be returned, how do I configure my custom exception handler where in I will stop the stack trace log in warning messages?
Thanks in advance.

**Comment by ragnor** [comment]
Hi,

The mechanism responsible for connecting to memcached server and
maintaining status of the connection is not part of Simple Spring Memcached
library. This part is covered and handled by the underlying provider. In
the case of xmemcached I don't see any logic that allows to modify the
reconnect strategy.
Sad to say but one of the possible solutions might be just
reconfigure logger to mute related exceptions.

-- RaGnoR
