### ISSUE TITLE
Advantage of elasticache client

### ISSUE THREAD

**Issue by fletchgqc** [ragnor/simple-spring-memcached#96]
I am able to connect to AWS elasticache using the XMemcached client, which is logical since AWS is Memcached-protocol-compatible.

What advantage would I get out of using the ElastiCache client? How should I decide which one to use?

**Comment by ragnor** [comment]
Probably the main feature of ElastiCache client is dedicated auto discovery memchanizm: https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/AutoDiscovery.html
